# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
registries:
  pdl:
    type: maven-repository
    url: https://maven.pkg.github.com/navikt/pdl
    username: x-access-token
    password: ${{ secrets.PDL_STUFF }}
updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: "daily"
    registry: pdl
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    cooldown:
      default-days: 7
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    cooldown:
      default-days: 7
