apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
    name: tilgangmaskin-alerts
    namespace: "tilgangsmaskin"
    labels:
      team: tilgangsmaskin
spec:
  groups:
    - name: client-errors
      rules:
        - alert: ApplikasjonNede
          expr: kube_deployment_status_replicas_available{namespace="tilgangsmaskin", deployment="populasjonstilgangskontroll"} == 0
          for: 2m
          annotations:
            consequence: tilgangsmaskin er nede
            action: "Ta en titt p책 Grafana og Kibana  test av melding til slack  ved 책 sei replica ulik 0"
            summary: |-
              Grafana: https://grafana.nav.cloud.nais.io/goto/LQb7lCfNg?orgId=1
              Loki securelogs: 
              Kibana securelogs: 
              Kibana 책pne logger:
          labels:
            namespace: tilgangsmaskin
            severity: critical
        - alert: ErrorLogMessages
          expr: sum(increase(log_messages_errors{app="populasjonstilgangskontroll", level="Error"}[10m])) > 0
          for: 1s
          annotations:
            consequence: tilgangsmaskin har feil i loggene
            action: "Ta en titt p책 Grafana og Kibana"
            summary: |-
              Grafana: https://grafana.nav.cloud.nais.io/goto/LQb7lCfNg?orgId=1
              
                Loki securelogs:
          labels:
            namespace: tilgangsmaskin
            severity: critical
        - alert: HttpClientErrorRateHigh
          expr: |
            1 - (
              sum(
                rate(
                  http_client_request_duration_seconds_count{app="populasjonstilgangskontroll.nav.no", http_response_status_code="200"}[5m]
                )
              ) by (server_address)
              /
              sum(
                rate(
                  http_client_request_duration_seconds_count{app="populasjonstilgangskontroll.nav.no"}[5m]
                )
              ) by (server_address)
            ) * 100 < 95
          for: 10m
          annotations:
            summary: "High error rate for outbound http requests"
            consequence: "Users are experiencing errors when using the application."
            action: "Check the logs using `kubectl logs` for errors and check upstream services."
            message: "Requests to `{{ $labels.server_address }}` are failing at {{ $value }}% over the last 5 minutes."
            runbook_url: ""
            dashboard_url: "https://grafana.nav.cloud.nais.io/"
          labels:
            severity: Error
            namespace: tilgangsmaskin
