apiVersion: "monitoring.coreos.com/v1"
kind: "PrometheusRule"
metadata:
  name: "warnings"
  namespace: "tilgangsmaskin"
  labels:
    team: "tilgangsmaskin"
spec:
  groups:
    - name: "tilgangsmaskin  alerts"
      rules:
        - alert: "[tilgangsmaskin] Forhøyede feilrater (warnings)"
          expr: sum(round(increase(logback_events_total{app="populasjonstilgangskontroll", level="warn"}[2m]))) > 20
          for: 3m
          annotations:
            action: "Sjekk loggene for å se hvorfor det er så mange advarsler"
          labels:
            namespace: "tilgangsmaskin"
            severity: warning
        - alert: "[tilgangsmaskin] Forhøyede feilrater (errors)"
          expr: sum(round(increase(logback_events_total{app="populasjonstilgangskontroll", level="error"}[2m]))) > 10
          for: 3m
          annotations:
            action: "Sjekk loggene for å se hvorfor det er så mange feil"
          labels:
            namespace: "tilgangsmaskin"
            severity: danger
        - alert: "[tilgangsmaskin] Helsesjekk ikke UP"
          expr: health{app="populasjonstilgangskontroll", namespace="tilgangsmaskin"} != 3
          for: 2m
          annotations:
            action: "Sjekk /monitoring/health for detaljer om hvilken komponent som er nede"
            consequence: "Applikasjonen rapporterer ikke UP — en eller flere avhengigheter kan være nede"
            summary: |-
              Grafana: https://grafana.nav.cloud.nais.io/d/42e329f6-6f6c-4365-84a1-7c65def92463/tilgangmaskin-prod?orgId=1
          labels:
            namespace: "tilgangsmaskin"
            severity: critical

