apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: enkeltilgang-v1
  namespace: tilgangsmaskin
  labels:
    team: tilgangsmaskin
spec:
  pool: nav-{{nais.cluster.type}}
  config:
    cleanupPolicy: delete
    retentionHours: 720 # 30 dager
  acl:
    - team: tilgangsmaskin
      application: populasjonstilgangskontroll
      access: write
