apiVersion: nais.io/v1alpha1
kind: Application

metadata:
  labels:
    team: tilgangsmaskin
  name: populasjonstilgangskontroll
  namespace: tilgangsmaskin
spec:
  ingresses:
     - {{ingressIntern}}
     - {{ingeressAnsatt}}
  image: {{image}}
  prometheus:
    enabled: true
    path: /monitoring/prometheus
  readiness:
    path: /monitoring/health/readiness
    initialDelay: 30
  liveness:
    path: /monitoring/health/liveness
    initialDelay: 30
  port: 8080
  replicas:
    max: 1
    min: 1
  resources:
    limits:
      memory: 1024Mi
    requests:
      cpu: 50m
      memory: 512Mi
  azure:
    application:
      enabled: true
      allowAllUsers: true
      claims:
        extra:
          - "NAVident"
          - "azp_name"
        groups:
          - id: '{{fortrolig}}'
          - id: '{{strengt}}'
          - id: '{{egenansatt}}'
  secureLogs:
    enabled: true
  accessPolicy:
    outbound:
      rules:
        - application: skjermede-personer-pip
          namespace: nom
      external:
        - host: {{pdl}}
    inbound:
      rules:
        - application: ida
          namespace: traktor
          cluster: prod-fss
  env:
    - name: NAIS_CLUSTER_TYPE
      value: {{nais.cluster.type}}
    - name: PDL
      value: {{pdl}}
    - name: GRUPPE_STRENGT
      value: '{{grupper.strengt}}'
    - name: GRUPPE_FORTROLIG
      value: '{{grupper.fortrolig}}'
    - name: GRUPPE_EGENANSATT
      value: '{{grupper.egenansatt}}'

