apiVersion: nais.io/v1alpha1
kind: Application

metadata:
  labels:
    team: tilgangsmaskin
  name: populasjonstilgangskontroll
  namespace: tilgangsmaskin
spec:
  gcp:
    sqlInstances:
      - type: {{db.type}}
        tier: {{db.tier}}
        databases:
        - name: {{db.name}}
          envVarPrefix: DB
        flags:
         - name: cloudsql.enable_pgaudit
           value: "{{db-flags.pgaudit.enabled}}"
         - name: pgaudit.log
           value: "{{db-flags.pgaudit.logtype}}"
  ingresses:
    {{#each ingresses as |ingress|}}
        - {{ingress}}
    {{/each}}
  image: {{image}}
  observability:
    autoInstrumentation:
        enabled: true
        runtime: java
  prometheus:
    enabled: true
    path: /monitoring/prometheus
  readiness:
    path: /monitoring/health/readiness
    initialDelay: 30
  liveness:
    path: /monitoring/health/liveness
    initialDelay: 30
  port: 8080
  replicas:
    max: {{replica.max}}
    min: {{replica.min}}
  resources:
    limits:
      memory: '{{mem.limit}}'
    requests:
      cpu: '{{cpu.min}}'
      memory: '{{mem.min}}'
  azure:
    application:
      enabled: true
      allowAllUsers: true
      claims:
        extra:
          - "NAVident"
          - "azp_name"
        groups:
          - id: '{{grupper.fortrolig}}'
          - id: '{{grupper.strengt}}'
          - id: '{{grupper.egenansatt}}'
  secureLogs:
    enabled: true
  accessPolicy:
    outbound:
      rules:
        - application: skjermede-personer-pip
          namespace: nom
      external:
        - host: {{pdl}}
        - host: {{pdlpip}}
    inbound:
      rules:
       {{#each inbound as |app|}}
        - application: '{{app.name}}'
          namespace: '{{app.namespace}}'
          cluster: '{{app.cluster}}'
       {{/each}}
  env:
    - name: NAIS_CLUSTER_TYPE
      value: {{nais.cluster.type}}
    - name: PDL
      value: {{pdl}}
    - name: PDLPIP
      value: {{pdlpip}}
    - name: GRUPPE_STRENGT
      value: '{{grupper.strengt}}'
    - name: GRUPPE_FORTROLIG
      value: '{{grupper.fortrolig}}'
    - name: GRUPPE_EGENANSATT
      value: '{{grupper.egenansatt}}'
    - name: GRUPPE_UDEFINERT
      value: '{{grupper.udefinert}}'
    - name: GRUPPE_NASJONAL
      value: '{{grupper.nasjonal}}'
    - name: GRUPPE_UTLAND
      value: '{{grupper.utland}}'
