apiVersion: nais.io/v1alpha1
kind: Application

metadata:
  labels:
    team: tilgangsmaskin
  name: populasjonstilgangskontroll
  namespace: tilgangsmaskin
spec:
  ingresses:
     - https://tilgangsmaskin.intern.dev.nav.no
  image: {{image}}
  prometheus:
    enabled: true
    path: /internal/prometheus
  readiness:
    path: /internal/health/readiness
    initialDelay: 22
  liveness:
    path: /internal/health/liveness
    initialDelay: 22
  port: 8080
  replicas:
    max: 1
    min: 1
  resources:
    limits:
      memory: 1024Mi
    requests:
      cpu: 50m
      memory: 512Mi
  azure:
    application:
      enabled: true
      allowAllUsers: true
      claims:
        extra:
          - azp_name
  secureLogs:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: gosys-q1
          namespace: isa

    outbound:
      rules:
        - application: skjermede-personer-pip
          namespace: nom

  env:
    - name: MICROSOFT_GRAPH_SCOPE
      value: https://graph.microsoft.com/.default
    - name: MICROSOFT_GRAPH_URL
      value: https://graph.microsoft.com
    - name: SKJERMET_PERSON_SCOPE
      value: api://dev-gcp.nom.skjermede-personer-pip/.default
    - name: SKJERMET_PERSON_URL
      value: http://skjermede-personer-pip.nom.svc.cluster.local
    - name: PDL_BASE_URL
      value: http://pdl-api.default.svc.cluster.local