apiVersion: nais.io/v1alpha1
kind: Application

metadata:
  labels:
    team: tilgangsmaskin
  name: populasjonstilgangskontroll
  namespace: tilgangsmaskin
spec:
  ingresses:
     - https://tilgangsmaskin.intern.dev.nav.no
  image: {{image}}
  prometheus:
    enabled: true
    path: /monitoring/prometheus
  readiness:
    path: /monitoring/health/readiness
    initialDelay: 22
  liveness:
    path: /monitoring/health/liveness
    initialDelay: 22
  port: 8080
  replicas:
    max: 1
    min: 1
  resources:
    limits:
      memory: 1024Mi
    requests:
      cpu: 50m
      memory: 512Mi
  azure:
    application:
      enabled: true
      allowAllUsers: true
      claims:
        extra:
          - azp_name
  secureLogs:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: gosys-q1
          namespace: isa

    outbound:
      rules:
        - application: skjermede-personer-pip
          namespace: nom
      external:
        - host: pdl-api.dev-fss-pub.nais.io
