apiVersion: nais.io/v1alpha1
kind: Application

metadata:
  labels:
    team: tilgangsmaskin
  name: populasjonstilgangskontroll
  namespace: tilgangsmaskin
spec:
  image: {{image}}
  prometheus:
    enabled: true
    path: /internal/prometheus
  readiness:
    path: /internal/health/readiness
    initialDelay: 22
  liveness:
    path: /internal/health/liveness
    initialDelay: 22
  port: 8080
  replicas:
    max: 1
    min: 1
  resources:
    requests:
      cpu: 50m
      memory: 32Mi
  azure:
    application:
      enabled: true
      allowAllUsers: true
      claims:
        extra:
          - azp_name
  secureLogs:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: gosys-q1
          namespace: isa

    outbound:
      rules:
        - application: skjermede-personer-pip
          namespace: nom
