apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: helsesjekker
  namespace: tilgangsmaskin
spec:
  interval: 60s
  module: http_2xx
  prober:
    path: /api/v0/component/prometheus.exporter.blackbox.blackbox_exporter/probe
    url: alloy.nais-system:12345
  targets:
    staticConfig:
      static:
      - http://populasjonstilgangskontroll.tilgangsmaskin/monitoring/health/entraProxy
      - http://populasjonstilgangskontroll.tilgangsmaskin/monitoring/health/graph
      - http://populasjonstilgangskontroll.tilgangsmaskin/monitoring/health/pdl
      - http://populasjonstilgangskontroll.tilgangsmaskin/monitoring/health/pdlGraph
      - http://populasjonstilgangskontroll.tilgangsmaskin/monitoring/health/skjerming
      - http://populasjonstilgangskontroll.tilgangsmaskin/monitoring/health/valKey
      - http://populasjonstilgangskontroll.tilgangsmaskin/monitoring/health/db

