apiVersion: aiven.io/v1alpha1
kind: Valkey
metadata:
  labels:
    app: populasjonstilgangskontroll
    team: tilgangsmaskin
  name: cache
  namespace: tilgangsmaskin
spec:
  terminationProtection: false
  plan: {{nais.cluster.plan}}
  project: nav-{{nais.cluster.type}}
  userConfig:
    valkey_maxmemory_policy: allkeys-lru