apiVersion: aiven.io/v1alpha1
kind: Valkey
metadata:
  labels:
    app: populasjonstilgangskontroll
    team: tilgangsmaskin
  name: valkey-tilgangsmaskin-cache
  namespace: tilgangsmaskin
spec:
  plan: startup-8
  project: nav-{{nais.cluster.type}}
  userConfig:
    valkey_maxmemory_policy: allkeys-lru