apiVersion: aiven.io/v1alpha1
kind: Valkey
metadata:
  labels:
    app: populasjonstilgangskontroll
    team: tilgangsmaskin
  name: valkey-tilgangsmaskin-cache
  namespace: tilgangsmaskin
spec:
  plan: {{nais.cluster.plan}}
  project: nav-{{nais.cluster.type}}
  integrationType: prometheus
  destinationEndpointId: {{nais.cluster.endpoint}}
  sourceServiceName: valkey-tilgangsmaskin-cache
  userConfig:
    valkey_maxmemory_policy: allkeys-lru