apiVersion: aiven.io/v1alpha1
kind: ServiceIntegration
metadata:
  labels:
    team: tilgangsmaskin
  name: valkey-tilgangsmaskin-cache
  namespace: tilgangsmaskin
spec:
  project: nav-dev
  integrationType: prometheus
  destinationEndpointId: f20f5b48-18f4-4e2a-8e5f-4ab3edb19733
  sourceServiceName: valkey-tilgangsmaskin-cache