spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/default/jwks
          audiences:
            - client id
  cache:
    type: caffeine

microsoft:
    graph:
      url: https://graph.microsoft.com/v1.0
      scope: https://graph.microsoft.com/.default