spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          authorities-claim-name: roles
          authority-prefix: ROLE_
  messages:
    basename:
      - messages
      - openapi/regel
      - regel-messages
      - openapi/prod/tilgang
management:
  endpoint:
    env:
      show-values: never
    configprops:
      show-values: never
    health:
      show-details: always
      show-components: always
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,caches

logbook:
  filter:
    enabled: false
  secure-filter:
    enabled: false