management:
  httpexchanges:
    recording:
      enabled: true
  health:
    ping:
      enabled: false
    diskspace:
      enabled: false
  endpoint:
    health:
      show-details: always
      show-components: always
    env:
      show-values: always
    configprops:
      show-values: always
  endpoints:
    web:
      base-path: /monitoring
      exposure:
        include: '*'

no.nav.security.jwt:
  issuer:
     azuread:
        discovery-url: ${azure.app.well.known.url}
        accepted_audience: ${azure.app.client.id}
  client:
    registration:
      pdl-api:
        token-endpoint-url: ${azure.openid.config.token.endpoint}
        grant-type: client_credentials
        scope: api://dev-fss.pdl.pdl-api/.default
        authentication:
          client-id: ${azure.app.client.id}
          client-jwk: ${azure.app.jwk}
          client-auth-method: private_key_jwt

springdoc:
    swagger-ui:
      csrf:
        enabled: true