spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/default
          accepted-audience: client id
  cache:
    type: caffeine

microsoft:
    graph:
      url: https://graph.microsoft.com/v1.0
      scope: https://graph.microsoft.com/.default