spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/default
      client:
        registration:
          onbehalfof:
            provider: azure
            authorization-grant-type: client_credentials
            scope: https://graph.microsoft.com/.default
            client-id: client id
        provider:
          azure:
            token-uri: https://login.microsoftonline.com/${AZURE_APP_TENANT_ID}/oauth2/v2.0/token
spring:
  cache:
    type: caffeine

microsoft:
    graph:
      url: https://graph.microsoft.com/v1.0
      scope: https://graph.microsoft.com/.default