spring:
  messages:
    basename:
      - messages
      - regel-messages
      - openapi-prod-tilgang
      - openapi/dev/ansatt
      - openapi/dev/bruker
      - openapi/dev/cache
      - openapi/dev/enkelt
      - openapi/dev/regel
      - openapi/dev/skjerming
      - openapi/dev/tilgang
      - openapi/dev/vergemal
    encoding: UTF-8
  mvc:
    log-request-details: true
management:
  endpoint:
    env:
      show-values: always
    configprops:
      show-values: always
    health:
      show-details: always
      show-components: always
  endpoints:
    web:
      exposure:
        include: '*'
info:
  client-id: ${azure.app.client.id}
