spring:
  mvc:
    log-request-details: true
management:
  endpoint:
    env:
      show-values: always
    configprops:
      show-values: always
    health:
      show-details: always
      show-components: always
  endpoints:
    web:
      exposure:
        include: '*'
info:
  client-id: ${azure.app.client.id}

app:
  messages:
    basenames:
      - messages
      - regel-messages
      - openapi-prod-tilgang
      - openapi/dev/openapi-dev-ansatt
      - openapi/dev/openapi-dev-bruker
      - openapi/dev/openapi-dev-cache
      - openapi/dev/openapi-dev-enkelt
      - openapi/dev/openapi-dev-regel
      - openapi/dev/openapi-dev-skjerming
      - openapi/dev/openapi-dev-tilgang
      - openapi/dev/openapi-dev-vergemal
