management:
  health:
    ping:
      enabled: false
    diskspace:
      enabled: false
  endpoints:
    web:
      base-path: /monitoring

no.nav.security.jwt:
  issuer:
     azuread:
        discovery-url: ${azure.app.well.known.url}
        accepted_audience: ${azure.app.client.id}
  client:
    registration:
      pdl-api:
        token-endpoint-url: ${azure.openid.config.token.endpoint}
        grant-type: client_credentials
        scope: ${pdl.scope}
        authentication:
          client-id: ${azure.app.client.id}
          client-jwk: ${azure.app.jwk}
          client-auth-method: private_key_jwt
      skjermede-personer-pip:
        token-endpoint-url: ${azure.openid.config.token.endpoint}
        grant-type: client_credentials
        scope: ${skjerming.scope}
        authentication:
          client-id: ${azure.app.client.id}
          client-jwk: ${azure.app.jwk}
          client-auth-method: private_key_jwt
springdoc:
    swagger-ui:
      csrf:
        enabled: true


pdl:
  scope: "api://${env}-fss.pdl.pdl-api/.default"
  base-uri: "https://${pdl}/graphql"
skjerming:
  base-uri: "http://skjermede-personer-pip.nom"
  scope: "api://${env}-gcp.nom.skjermede-personer-pip/.default"
graph:
  base-uri: https://www.todo.no
  scope: api://${env}-gcp.todo/.default
