openapi.dev.tilgang.tag.description=Denne kontrolleren skal kun brukes til testing
openapi.dev.tilgang.oppfolging.avslutt.summary=Avslutt oppfølging for en gitt UUID og identer
openapi.dev.tilgang.oppfolging.avslutt.description=Avslutter oppfølging for oppgitt UUID basert på identer i request body.
openapi.dev.tilgang.oppfolging.enhet.summary=Hent enhet for en identifikator
openapi.dev.tilgang.oppfolging.enhet.description=Henter oppfølgingsenhet for oppgitt identifikator.
openapi.dev.tilgang.sivilstand.summary=Hent sivilstand og partnerrelasjoner
openapi.dev.tilgang.sivilstand.description=Henter partnerrelasjoner fra PDL for oppgitt ident.
openapi.dev.tilgang.kobling.summary=Sette kobling mellom ansatt og fnr
openapi.dev.tilgang.kobling.description=Funksjon for å opprette relasjon mellom nav-ident og fnr slik at oppslag på egne data og familierelasjoner kan testes.
openapi.dev.tilgang.nom.fnr.summary=Hent fnr koblet til ansatt
openapi.dev.tilgang.nom.fnr.description=Henter fnr-kobling for oppgitt ansatt-ident fra NOM-tabellen.
openapi.dev.tilgang.overstyr.summary=Overstyr regler for en bruker
openapi.dev.tilgang.overstyr.description=Setter overstyring for en bruker, slik at den kan saksbehandles selv om saksbehandler opprinnelig ikke har tilgang. BrukerId må være gyldig og finnes i PDL. Kjerneregelsettet vil bli kjørt før overstyring, og hvis de feiler vil overstyring ikke bli gjort. Overstyring vil gjelde frem til og med utløpsdatoen.
openapi.dev.tilgang.overstyringer.summary=Hent overstyringer for en ansatt og en eller flere brukere
openapi.dev.tilgang.overstyringer.description=Henter overstyringer for en eller flere brukere.

