openapi.dev.cache.tag.description=Denne kontrolleren skal kun brukes til testing
openapi.dev.cache.skjerminger.summary=Hent cachede skjerminger
openapi.dev.cache.skjerminger.description=Henter cachet skjermingstatus for oppgitte NAV-identer.
openapi.dev.cache.personer.summary=Hent cachede personer
openapi.dev.cache.personer.description=Henter cachede personoppslag for oppgitte identifikatorer.

