openapi.tilgang.tag.description=Denne kontrolleren skal brukes i produksjon
openapi.tilgang.komplett.obo.summary=Evaluer komplett regelsett for en bruker (obo)
openapi.tilgang.komplett.obo.description=Evaluer komplett regelsett for en bruker (obo)
openapi.tilgang.komplett.ccf.summary=Evaluer et komplett regelsett for en bruker (ccf)
openapi.tilgang.komplett.ccf.description=Evaluer et komplett regelsett for en bruker (ccf)
openapi.tilgang.kjerne.obo.summary=Evaluer  kjerneregler for en bruker (obo)
openapi.tilgang.kjerne.ccf.summary=Evaluer kjerneregler for en bruker (ccf)
openapi.tilgang.kjerne.obo.description=Evaluer kjerneregler for en bruker (obo)
openapi.tilgang.kjerne.ccf.description=Evaluer kjerneregler for en bruker (ccf)
openapi.tilgang.overstyr.summary=Overstyr regler for en bruker (obo)
openapi.tilgang.overstyr.description=Setter overstyring for en bruker (obo)
openapi.tilgang.bulk.summary=Evaluer regler for et sett med brukere (obo)
openapi.tilgang.bulk.obo.description=Evaluer regler for et sett med brukere (obo)
openapi.tilgang.bulk.obo.regeltype.description=Evaluer regler for et sett av brukere og gitte regeltyper (obo)
openapi.tilgang.bulk.ccf.description=Evaluer regler for et sett av brukere og regeltyper (ccf)
openapi.tilgang.bulk.ccf.regeltype.description=Evaluer regler for et sett av brukere og regeltyper (ccf)

