openapi.dev.ansatt.tag.description=Denne kontrolleren skal kun brukes til testing
openapi.dev.ansatt.ansatt.summary=Hent ansattdata
openapi.dev.ansatt.ansatt.description=Henter ansattinformasjon for oppgitt ansatt-id.
openapi.dev.ansatt.proxy.enhet.summary=Hent enhet via Entra Proxy
openapi.dev.ansatt.proxy.enhet.description=Henter enhet for oppgitt ansatt-id via Entra Proxy.
openapi.dev.ansatt.proxy.enheter.summary=Hent enheter via Entra Proxy
openapi.dev.ansatt.proxy.enheter.description=Henter alle enheter for oppgitt ansatt-id via Entra Proxy.

