openapi.dev.regel.tag.description=Denne kontrolleren skal kun brukes til testing
openapi.dev.regel.komplett.summary=Kjor komplett regelsett for en ansatt og bruker
openapi.dev.regel.komplett.description=Kjorer komplett regelsett for oppgitt ansatt og bruker i dev.
openapi.dev.regel.kjerne.summary=Kjor kjerneregelsett for en ansatt og bruker
openapi.dev.regel.kjerne.description=Kjorer kjerneregelsett for oppgitt ansatt og bruker i dev.
openapi.dev.regel.bulk.summary=Kjor bulkregler for en ansatt
openapi.dev.regel.bulk.description=Kjorer regelvurdering i bulk for oppgitt ansatt med eksplisitte spesifikasjoner.
openapi.dev.regel.bulk.regeltype.summary=Kjor bulkregler for en ansatt og regeltype
openapi.dev.regel.bulk.regeltype.description=Kjorer regelvurdering i bulk for oppgitt ansatt og regeltype.

