openapi.dev.regel.tag.description=Denne kontrolleren skal kun brukes til testing
openapi.dev.regel.komplett.summary=Kjør komplett regelsett for en ansatt og bruker
openapi.dev.regel.komplett.description=Kjører komplett regelsett for oppgitt ansatt og bruker i dev.
openapi.dev.regel.kjerne.summary=Kjør kjerneregelsett for en ansatt og bruker
openapi.dev.regel.kjerne.description=Kjører kjerneregelsett for oppgitt ansatt og bruker i dev.
openapi.dev.regel.bulk.summary=Kjør bulkregler for en ansatt
openapi.dev.regel.bulk.description=Kjører regelvurdering i bulk for oppgitt ansatt med eksplisitte spesifikasjoner.
openapi.dev.regel.bulk.regeltype.summary=Kjør bulkregler for en ansatt og regeltype
openapi.dev.regel.bulk.regeltype.description=Kjører regelvurdering i bulk for oppgitt ansatt og regeltype.

