openapi.dev.vergemal.tag.description=Denne kontrolleren skal kun brukes til testing
openapi.dev.vergemal.vergemal.summary=Hent vergemal for ansatt
openapi.dev.vergemal.vergemal.description=Henter vergemalsinformasjon for oppgitt ansatt.

