openapi.tilgang.tag.description=Denne kontrolleren skal brukes i produksjon
openapi.tilgang.komplett.obo.summary=Evaluer komplett regelsett for bruker
openapi.tilgang.komplett.obo.description=Evaluer komplett regelsett for bruker
openapi.tilgang.komplett.ccf.summary=Evaluer et komplett regelsett for bruker
openapi.tilgang.komplett.ccf.description=Evaluer et komplett regelsett for bruker
openapi.tilgang.kjerne.obo.summary=Evaluer  kjerneregler for bruker
openapi.tilgang.kjerne.ccf.summary=Evaluer kjerneregler for bruker
openapi.tilgang.kjerne.obo.description=Evaluer kjerneregler for bruker
openapi.tilgang.kjerne.ccf.description=Evaluer kjerneregler for bruker
openapi.tilgang.overstyr.summary=Gi enkelttilgang for bruker
openapi.tilgang.overstyr.description=Gi enkelttilgang for bruker
openapi.tilgang.bulk.summary=Evaluer regler for et sett med brukere
openapi.tilgang.bulk.obo.description=Evaluer regler for et sett med brukere
openapi.tilgang.bulk.obo.regeltype.description=Evaluer regler for et sett med brukere og gitte regeltyper
openapi.tilgang.bulk.ccf.description=Evaluer regler for et sett av brukere og regeltyper
openapi.tilgang.bulk.ccf.regeltype.description=Evaluer regler for et sett av brukere og regeltyper

