openapi.dev.bruker.tag.description=Denne kontrolleren skal kun brukes til testing
openapi.dev.bruker.person.pip.summary=Hent person fra PDL PIP
openapi.dev.bruker.person.pip.description=Henter persondata via PDL PIP for oppgitt ident.
openapi.dev.bruker.person.summary=Hent person med utvidet familie
openapi.dev.bruker.person.description=Henter person med utvidede familierelasjoner for oppgitt ident.
openapi.dev.bruker.brukere.summary=Hent flere brukere
openapi.dev.bruker.brukere.description=Henter brukerdata for et sett av brukeridenter.
openapi.dev.bruker.brukeridentifikator.summary=Hent bruker via identifikator
openapi.dev.bruker.brukeridentifikator.description=Henter bruker med utvidet familie basert på identifikator i request body.
openapi.dev.bruker.bruker.summary=Hent bruker med utvidet familie
openapi.dev.bruker.bruker.description=Henter bruker med utvidet familie for oppgitt ident.

