openapi.dev.skjerming.tag.description=Denne kontrolleren skal kun brukes til testing
openapi.dev.skjerming.skjerming.summary=Hent skjerming for en bruker
openapi.dev.skjerming.skjerming.description=Henter skjermingstatus for oppgitt bruker.
openapi.dev.skjerming.skjerminger.summary=Hent skjerming for flere brukere
openapi.dev.skjerming.skjerminger.description=Henter skjermingstatus for oppgitte brukere.

