openapi.dev.enkelt.tag.description=Denne kontrolleren skal kun brukes til testing av enkelttilgang
openapi.dev.enkelt.summary=Registrer enkelttilgang for en ansatt og bruker
openapi.dev.enkelt.description=Registrerer enkelttilgang for oppgitt ansatt-id og bruker-id med begrunnelse 'test'. Kun tilgjengelig i dev.
openapi.dev.enkelt.har=Sjekk om ansatt har enkelttilgang til bruker
openapi.dev.enkelt.har.description=Sjekker om oppgitt ansatt har aktiv enkelttilgang til oppgitt bruker.
