name: Copilot Customization Sync
on:
  schedule:
    - cron: '0 7 * * 1'  # Mandager kl. 07:00 UTC
  workflow_dispatch:
jobs:
  sync:
    uses: navikt/copilot/.github/workflows/copilot-customization-sync.yml@7acbe01f5609d6079a1a05d6187079a772705a95 # main
    permissions:
      contents: write
      pull-requests: write