name: Build and deploy
on:
  push:
    branches:
      - main
env:
  IMAGE: europe-north1-docker.pkg.dev/nais-management-233d/tilgangsmaskin/${{ github.event.repository.name }}
jobs:
  build:
    name: build
    permissions:
      checks: write
      contents: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Sjekker ut kode
        uses: actions/checkout@v4

      - name: Cache
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Install Java 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      - name: Installerer cosign
        uses: sigstore/cosign-installer@main
        with:
          cosign-release: v2.4.1


      - name: Setter tag-navn
        run: echo "TAG=$(date +%Y.%m.%d.%H%M%S)-$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

      - name: Login GAR
        uses: nais/login@v0
        with:
          team: tilgangsmaskin

      - name: Test og bygg
        id: kompiler
        run: |
          echo "image=${{ env.IMAGE }}:${{ env.TAG }}" >> $GITHUB_OUTPUT    
          ./gradlew test jib -Djib.to.tags=latest,${TAG} -Djib.to.image=${{ env.IMAGE }}:${{ env.TAG }}
          echo "DIGEST=$(cat build/jib-image.digest)" >> $GITHUB_ENV
        env:
          ORG_GRADLE_PROJECT_githubUser: x-access-token
          ORG_GRADLE_PROJECT_githubPassword: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v4

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v5
        if: always() # always run even if the previous step fails
        with:
          include_time_in_summary: 'true'
          include_passed: 'true'
          detailed_summary: 'true'
          report_paths: '**/build/test-results/test/TEST-*.xml'

      - name: Attest and sign
        uses: nais/attest-sign@v1.5.17
        with:
          image_ref: ${{env.IMAGE}}@${{env.DIGEST}}
          sbom: build/reports/application.cdx.json

    outputs:
      image: ${{ steps.kompiler.outputs.image }}

  deploy:
    permissions:
      contents: write
      id-token: write
    strategy:
      matrix:
        cluster: [ dev-gcp, prod-gcp ]
    name: Deploy til ${{matrix.cluster}}
    needs: build
    runs-on: ubuntu-latest
    environment: ${{matrix.cluster}}:tilgangsmaskin
    env:
      PRINT_PAYLOAD: true
      TIMEOUT: 30m
      RESOURCE: .nais/naiserator.yaml,.nais/probes.yaml,.nais/probe-alerts.yaml,.nais/valkey.yaml,.nais/serviceintegration.yaml
      CLUSTER: ${{matrix.cluster}}
      VARS: .nais/${{matrix.cluster}}.json
      IMAGE: ${{needs.build.outputs.image}}
    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v2
