name: Build and deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    name: "Bygger app og deployer til dev-gcp"
    uses: navikt/populasjonstilgangskontroll/.github/workflows/java-build-and-deploy.yml@main
    secrets: inherit
    permissions:
      id-token: write
    with:
      cluster: "dev-gcp"
      manifest: ".nais/preprod.yaml"
      skip-checks: ${{ github.event.inputs.skip-checks == true }}