name: Build and deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Install Java 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      - name: Test and build
        run: ./gradlew build
        env:
          ORG_GRADLE_PROJECT_githubUser: x-access-token
          ORG_GRADLE_PROJECT_githubPassword: ${{ secrets.GITHUB_TOKEN }}

      - name: build artifact
        run: ./gradlew bootJar

      - name: Build & push Docker GAR
        uses: nais/docker-build-push@v0
        id: docker-build-push
        env:
          ACTIONS_RUNTIME_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
        with:
          team: tilgangsmaskin # required
          tag: ${{ github.sha }} # optional
          cache_to: type=gha,mode=max # optional, default type=gha,mode=max
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }} # required, but is defined as an organization secret
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }} # required, but is defined as an organization variable
    outputs:
      image: "${{ steps.docker-build-push.outputs.image }}"
  

      

  deploy_to_dev:
    name: Deploy
    needs: build
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout code

      - name: Deploy to dev
        uses: nais/deploy/actions/deploy@v2
        env:
          TEAM: tilgangsmaskin
          CLUSTER: dev-gcp
          RESOURCE: ./.nais/preprod.yaml
          IMAGE: ${{ needs.build.outputs.image }}
          DEPLOY_SERVER: deploy.nav.cloud.nais.io:443


