name: Build and deploy
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    name: Build, push and deploy
    runs-on: ubuntu-latest
    uses: navikt/populasjonstilgangskontroll/.github/workflows/java-docker-build-push.yml@main
    permissions:
      contents: write
      id-token: write